spring:
  profiles:
    active: local # 기본적으로 local이 선택된다는 뜻
  redis:
    host: localhost
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/readit?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: sbs123414
  mail:
    host: smtp.gmail.com
    port: 587
    username: jnnna77@gmail.com
    password: tlcbaomkiemftufh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  type-aliases-package: com.sbs.cyj.readit.dto
server:
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
    include-binding-errors: always
custom:
  logoText: readit
  emailFrom: no-reply@ilcho.site
  emailFromName: ReadIt

---

spring:
  profiles: local
server:
  port: 8085
  
---

spring:
  profiles: production
  servlet:
    multipart:
      location: /tmp
  datasource:
    username: juinLocal
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/readit?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull 